version: "2"

services:
  # services_realtime_chat_app:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   volumes:
  #     - ../services-realtime-chat-app:/go/src/go-with-compose
  #   working_dir: /go/src/go-with-compose
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - CONNECTION_DB=mongodb://mongodb_realtime_chat_app:27017
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mongodb_realtime_chat_app
  mongodb_realtime_chat_app:
    image: mongo:latest
    container_name: "mongodb_realtime_chat_app"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27019:27017"
    command: mongod  --logpath=/dev/null #
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
